{
 "title": "Grafana Image Rendering Service",
 "description": "Monitor the Grafana Image Renderer plugin when running it as a remote rendering service.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(grafana_image_renderer_browser_info > 0)"
    }
   ]
  },
  {
   "title": "Browser version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, grafana_image_renderer_browser_info)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Requests per second (by status)",
   "type": "graph",
   "description": "Average requests per second during past interval grouped by status codes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (label_replace(label_replace(rate(grafana_image_renderer_service_http_request_duration_seconds_count[$__interval]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\",   \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum without(instance,status_code)(\n    rate(grafana_image_renderer_service_http_request_duration_seconds_bucket[$__interval])\n  )\n)",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, \n  sum without(instance,status_code)(\n    rate(grafana_image_renderer_service_http_request_duration_seconds_bucket[$__interval])\n  )\n)",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum without(instance,status_code) (rate(grafana_image_renderer_service_http_request_duration_seconds_sum[$__interval])) \n/ \nsum without(instance,status_code) (rate(grafana_image_renderer_service_http_request_duration_seconds_count[$__interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Requests per second (by instance)",
   "type": "graph",
   "description": "Average requests per second during past interval grouped by instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(grafana_image_renderer_service_http_request_duration_seconds_count[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request latency distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(grafana_image_renderer_service_http_request_duration_seconds_bucket[$__interval]) * $__interval_ms / 1000) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}