version: "3.9"

services:
  app:
    image: ${NGINX_IMAGE}
    container_name: app
    restart: always
    environment:
      - TZ=Europe/Moscow
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
      - ./socket:/var/run/php
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - app
    depends_on:
      - wordpress

  wordpress:
    image: ${PHP_IMAGE}
    container_name: wordpress
    restart: always
    volumes:
      - /root/certs:/certs
      - ./zz.conf:/usr/local/etc/php-fpm.d/zz.conf
      - ./php.conf.ini:/usr/local/etc/php/conf.d/php.ini
      - ./wordpress:/var/www/html
      - ./socket:/var/run/php
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_SSL_KEY=/certs/client.key
      - MYSQL_SSL_CERT=/certs/client.crt
      - MYSQL_SSL_CA=/certs/CA.crt
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
    networks:
      - app

networks:
  app:
